### PR TITLE
#3 - Update to be compatible with WPGraphQL v0.8.3

### PR DESCRIPTION
**Pull request by jasonbahl**
This PR brings things up to speed with WPGraphQL v0.8.3

**Note that WPGraphQL v0.8.0, v0.8.1 and v0.8.2 won't work with this plugin**, because I foolishly made some methods protected in the v0.8.0 release which effectively made it so they couldn't be used from within filters like this plugin uses. 🤦‍♂️

### CODE REVIEW

**Comment by jasonbahl** [comment]
Closes #3

**Comment by jasonbahl** [comment]
See: https://github.com/wp-graphql/wp-graphql/pull/1241

**Comment by esamattis** [comment]
Added some environment fixes, but there's a real issue too. I see that `get_items()` is now gone but `get_nodes()` is not actually equivalent because it does array_slicing. This plugin wants do it by itself:

https://github.com/valu-digital/wp-graphql-offset-pagination/blob/4ab4f3c49c47937ae2838e484fda8bbca7dee018/src/Loader.php#L89

`get_nodes()`:

https://github.com/wp-graphql/wp-graphql/blob/c3f6b733fcb4f11f9789aeb93e6015f4d8e61348/src/Data/Connection/AbstractConnectionResolver.php#L544

And there's a conflict.

The important test for this is this

```
✖ PostPaginationTest: Conent nodes can have page bigger than default cursor
```

Which can be run from the testing shell with

```
codecept run wpunit tests/wpunit/PostPaginationTest.php:testConentNodesCanHavePageBiggerThanDefaultCursor
```

I think I need to rewrite the `get_nodes()` completely for wp-graphql-offset-pagination, but currently it is not possible because `$this->ids` is private. 

Any ideas how to proceed?

**Comment by jasonbahl** [comment]
@esamattis Gah. I'll make `get_ids()` a public function.

**Comment by jasonbahl** [comment]
@esamattis it looks like `$this->get_ids()` is public already.

**Pull request merged**
